# Generated by Django 3.2.4 on 2021-06-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(default='no_picture.png', upload_to='products')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(help_text='En Pesos colombianos')),
                ('unit_measure', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
